FROM python:3.10-slim

WORKDIR /app

COPY serve.py ./
COPY model ./model   

RUN pip install --no-cache-dir fastapi uvicorn pandas numpy tensorflow prometheus-fastapi-instrumentator

EXPOSE 8000

CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]
